# Generated by Django 5.2.6 on 2025-11-09 08:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید به فرمت 09123456789 باشد', regex='^09\\d{9}$')], verbose_name='شماره تماس')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='تصویر پروفایل')),
                ('wallet_balance', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='موجودی کیف پول')),
                ('clash_royale_tag', models.CharField(blank=True, help_text='مثال: #ABC123XYZ', max_length=20, null=True, unique=True, verbose_name='تگ کلش رویال')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournaments_played', models.PositiveIntegerField(default=0, verbose_name='تورنومنت\u200cهای بازی شده')),
                ('tournaments_won', models.PositiveIntegerField(default=0, verbose_name='تورنومنت\u200cهای برنده شده')),
                ('total_matches', models.PositiveIntegerField(default=0, verbose_name='مجموع بازی\u200cها')),
                ('matches_won', models.PositiveIntegerField(default=0, verbose_name='بازی\u200cهای برده')),
                ('total_earnings', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مجموع درآمد')),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد برد')),
                ('ranking', models.PositiveIntegerField(default=0, verbose_name='رتبه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آمار کاربر',
                'verbose_name_plural': 'آمار کاربران',
                'db_table': 'user_stats',
            },
        ),
    ]
