# Generated by Django 5.2.7 on 2025-11-11 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="ایمیل"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="شماره تلفن باید به فرمت 09123456789 باشد",
                        regex="^09\\d{9}$",
                    )
                ],
                verbose_name="شماره تماس",
            ),
        ),
    ]
