# Generated by Django 5.2.6 on 2025-11-09 08:39

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='اسلاگ')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='tournament_banners/%Y/%m/', verbose_name='بنر')),
                ('game_mode', models.CharField(choices=[('normal', 'normal'), ('double_elixir_battle', 'double elixir battle'), ('triple_elixir_battle', 'triple elixir battle'), ('sudden_death_battle', 'sudden death battle'), ('double_elixir_draft', 'double elixir draft'), ('triple_draft', 'triple draft'), ('heist_draft', 'heist draft'), ('hog_race', 'hog race'), ('lumberjack_rash', 'lumberjack rash'), ('wall_breaker_party', 'wall breaker party'), ('ghost_parade', 'ghost parade'), ('elixir_capture', 'elixir capture'), ('dragon_hunt', 'dragon hunt'), ('duel', 'duel'), ('mega_draft_challenge', 'mega draft challenge')], default='normal', max_length=30, verbose_name='حالت بازی')),
                ('pricable', models.CharField(choices=[('free', 'رایگان'), ('premium', 'پرمیوم')], default='premium', max_length=20, verbose_name='رایگان یا پولی')),
                ('max_participants', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(1000)], verbose_name='حداکثر شرکت\u200cکننده')),
                ('level_cap', models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(14)], verbose_name='لول کارتها')),
                ('max_losses', models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='حداکثر باخت مجاز')),
                ('time_duration', models.CharField(choices=[('30m', '30m'), ('1h', '1h'), ('2h', '2h'), ('3h', '3h'), ('4h', '4h')], default='1h', max_length=3, verbose_name='مدت تایم بازی')),
                ('entry_fee', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='هزینه ورودی')),
                ('prize_pool', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='جایزه کل')),
                ('platform_commission', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='کمیسیون پلتفرم (%)')),
                ('registration_start', models.DateTimeField(verbose_name='شروع ثبت\u200cنام')),
                ('registration_end', models.DateTimeField(verbose_name='پایان ثبت\u200cنام')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار'), ('registration', 'ثبت\u200cنام'), ('ready', 'آماده شروع'), ('ongoing', 'در حال برگزاری'), ('finished', 'پایان یافته'), ('cancelled', 'لغو شده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت')),
                ('rules', ckeditor.fields.RichTextField(blank=True, verbose_name='قوانین')),
                ('best_of', models.PositiveIntegerField(default=8, help_text='Best of 3, 5, 7', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='نفرات برتر')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('clash_royale_tournament_tag', models.CharField(blank=True, help_text='مثال: #ABC123XYZ', max_length=20, null=True, verbose_name='تگ تورنمنت کلش رویال')),
                ('tournament_password', models.CharField(blank=True, help_text='رمز تورنمنت کلش رویال برای اشتراک با بازیکنان', max_length=50, null=True, verbose_name='رمز تورنمنت')),
                ('auto_tracking_enabled', models.BooleanField(default=False, help_text='فعال\u200cسازی دریافت خودکار battle logs از کلش رویال', verbose_name='ردیابی خودکار فعال')),
                ('last_battle_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='آخرین زمان همگام\u200cسازی بازی\u200cها')),
                ('tracking_started_at', models.DateTimeField(blank=True, help_text='زمان شروع ردیابی بازی\u200cها - معمولاً زمان شروع تورنمنت', null=True, verbose_name='زمان شروع ردیابی')),
                ('total_participants', models.PositiveIntegerField(default=0, verbose_name='تعداد شرکت\u200cکننده')),
                ('total_matches', models.PositiveIntegerField(default=0, verbose_name='تعداد مسابقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'تورنومنت',
                'verbose_name_plural': 'تورنومنت\u200cها',
                'db_table': 'tournaments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000, verbose_name='پیام')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_tournament_messages', to=settings.AUTH_USER_MODEL, verbose_name='حذف شده توسط')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='tournaments.tournamentchat', verbose_name='پاسخ به')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_tournament_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='tournaments.tournament', verbose_name='تورنمنت')),
            ],
            options={
                'verbose_name': 'چت تورنمنت',
                'verbose_name_plural': 'چت\u200cهای تورنمنت',
                'db_table': 'tournament_chats',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='کد دعوت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شده'), ('declined', 'رد شده'), ('expired', 'منقضی شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('message', models.TextField(blank=True, verbose_name='پیام')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tournament_invitations', to=settings.AUTH_USER_MODEL, verbose_name='دعوت شده توسط')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_invitations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر دعوت شده')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tournaments.tournament', verbose_name='تورنومنت')),
            ],
            options={
                'verbose_name': 'دعوت\u200cنامه تورنومنت',
                'verbose_name_plural': 'دعوت\u200cنامه\u200cهای تورنومنت',
                'db_table': 'tournament_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('disqualified', 'محروم شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('placement', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='رتبه')),
                ('prize_won', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='جایزه برنده شده')),
                ('matches_played', models.PositiveIntegerField(default=0, verbose_name='مسابقات انجام شده')),
                ('matches_won', models.PositiveIntegerField(default=0, verbose_name='مسابقات برده')),
                ('disqualification_reason', models.TextField(blank=True, verbose_name='دلیل محرومیت')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_participant', to='payments.payment', verbose_name='پرداخت')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament', verbose_name='تورنومنت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شرکت\u200cکننده تورنومنت',
                'verbose_name_plural': 'شرکت\u200cکنندگان تورنومنت',
                'db_table': 'tournament_participants',
                'ordering': ['placement', '-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerBattleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_time', models.DateTimeField(db_index=True, help_text='زمان بازی از API کلش رویال', verbose_name='زمان بازی')),
                ('battle_type', models.CharField(choices=[('tournament', 'تورنمنت'), ('PvP', 'PvP'), ('challenge', 'چلنج'), ('friendly', 'دوستانه'), ('other', 'سایر')], default='tournament', max_length=20, verbose_name='نوع بازی')),
                ('game_mode', models.CharField(blank=True, max_length=50, verbose_name='حالت بازی')),
                ('player_tag', models.CharField(max_length=20, verbose_name='تگ بازیکن')),
                ('player_name', models.CharField(max_length=100, verbose_name='نام بازیکن')),
                ('player_crowns', models.PositiveIntegerField(default=0, verbose_name='تاج بازیکن')),
                ('player_king_tower_hp', models.PositiveIntegerField(blank=True, null=True, verbose_name='HP برج پادشاه بازیکن')),
                ('player_princess_towers_hp', models.JSONField(blank=True, default=list, verbose_name='HP برج\u200cهای پرنسس بازیکن')),
                ('opponent_tag', models.CharField(max_length=20, verbose_name='تگ حریف')),
                ('opponent_name', models.CharField(max_length=100, verbose_name='نام حریف')),
                ('opponent_crowns', models.PositiveIntegerField(default=0, verbose_name='تاج حریف')),
                ('opponent_king_tower_hp', models.PositiveIntegerField(blank=True, null=True, verbose_name='HP برج پادشاه حریف')),
                ('opponent_princess_towers_hp', models.JSONField(blank=True, default=list, verbose_name='HP برج\u200cهای پرنسس حریف')),
                ('is_winner', models.BooleanField(default=False, verbose_name='برنده')),
                ('is_draw', models.BooleanField(default=False, verbose_name='مساوی')),
                ('player_cards', models.JSONField(blank=True, default=list, help_text='لیست کارت\u200cهای استفاده شده', verbose_name='کارت\u200cهای بازیکن')),
                ('opponent_cards', models.JSONField(blank=True, default=list, verbose_name='کارت\u200cهای حریف')),
                ('arena_name', models.CharField(blank=True, max_length=100, verbose_name='نام آرنا')),
                ('arena_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه آرنا')),
                ('raw_battle_data', models.JSONField(blank=True, default=dict, help_text='داده کامل از API برای آینده', verbose_name='داده خام بازی')),
                ('is_counted', models.BooleanField(default=True, help_text='آیا در رتبه\u200cبندی محاسبه شود', verbose_name='محاسبه شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_logs', to='tournaments.tournament', verbose_name='تورنمنت')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_logs', to='tournaments.tournamentparticipant', verbose_name='شرکت\u200cکننده')),
            ],
            options={
                'verbose_name': 'لاگ بازی بازیکن',
                'verbose_name_plural': 'لاگ\u200cهای بازی بازیکنان',
                'db_table': 'player_battle_logs',
                'ordering': ['-battle_time'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(db_index=True, verbose_name='رتبه')),
                ('total_battles', models.PositiveIntegerField(default=0, verbose_name='تعداد بازی')),
                ('total_wins', models.PositiveIntegerField(default=0, verbose_name='تعداد برد')),
                ('total_losses', models.PositiveIntegerField(default=0, verbose_name='تعداد باخت')),
                ('total_draws', models.PositiveIntegerField(default=0, verbose_name='تعداد مساوی')),
                ('total_crowns', models.PositiveIntegerField(default=0, verbose_name='مجموع تاج\u200cها')),
                ('total_crowns_lost', models.PositiveIntegerField(default=0, verbose_name='مجموع تاج\u200cهای از دست رفته')),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, help_text='درصد برد (0-100)', max_digits=5, verbose_name='درصد برد')),
                ('score', models.PositiveIntegerField(default=0, help_text='امتیاز محاسبه شده برای رتبه\u200cبندی', verbose_name='امتیاز')),
                ('last_battle_time', models.DateTimeField(blank=True, null=True, verbose_name='آخرین بازی')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='زمان محاسبه')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='tournaments.tournamentparticipant', verbose_name='شرکت\u200cکننده')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='tournaments.tournament', verbose_name='تورنمنت')),
            ],
            options={
                'verbose_name': 'رتبه\u200cبندی تورنمنت',
                'verbose_name_plural': 'رتبه\u200cبندی\u200cهای تورنمنت',
                'db_table': 'tournament_rankings',
                'ordering': ['rank'],
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status', 'registration_start'], name='tournaments_status_7f141e_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['start_date'], name='tournaments_start_d_47803f_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['is_featured'], name='tournaments_is_feat_6a1b87_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['slug'], name='tournaments_slug_fe5094_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentchat',
            index=models.Index(fields=['tournament', 'created_at'], name='tournament__tournam_a42b74_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentchat',
            index=models.Index(fields=['sender', '-created_at'], name='tournament__sender__6e7352_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentchat',
            index=models.Index(fields=['tournament', 'is_deleted'], name='tournament__tournam_2b99da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentinvitation',
            unique_together={('tournament', 'invited_user')},
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['tournament', 'status'], name='tournament__tournam_7e318a_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['user', '-joined_at'], name='tournament__user_id_c46eda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together={('tournament', 'user')},
        ),
        migrations.AddIndex(
            model_name='playerbattlelog',
            index=models.Index(fields=['tournament', 'participant', '-battle_time'], name='player_batt_tournam_88bd15_idx'),
        ),
        migrations.AddIndex(
            model_name='playerbattlelog',
            index=models.Index(fields=['player_tag', '-battle_time'], name='player_batt_player__b418b1_idx'),
        ),
        migrations.AddIndex(
            model_name='playerbattlelog',
            index=models.Index(fields=['tournament', 'is_counted'], name='player_batt_tournam_97d38c_idx'),
        ),
        migrations.AddIndex(
            model_name='playerbattlelog',
            index=models.Index(fields=['battle_time'], name='player_batt_battle__4c4fad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerbattlelog',
            unique_together={('tournament', 'player_tag', 'battle_time', 'opponent_tag')},
        ),
        migrations.AddIndex(
            model_name='tournamentranking',
            index=models.Index(fields=['tournament', 'rank'], name='tournament__tournam_45d6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentranking',
            index=models.Index(fields=['tournament', '-score'], name='tournament__tournam_56c12b_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentranking',
            index=models.Index(fields=['-score'], name='tournament__score_4e7a38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentranking',
            unique_together={('tournament', 'participant')},
        ),
    ]
