# Generated by Django 5.2.6 on 2025-11-03 16:49

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='اسلاگ')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='tournament_banners/%Y/%m/', verbose_name='بنر')),
                ('game_mode', models.CharField(choices=[('normal', 'normal'), ('double_elixir_battle', 'double elixir battle'), ('triple_elixir_battle', 'triple elixir battle'), ('sudden_death_battle', 'sudden death battle'), ('double_elixir_draft', 'double elixir draft'), ('triple_draft', 'triple draft'), ('heist_draft', 'heist draft'), ('hog_race', 'hog race'), ('lumberjack_rash', 'lumberjack rash'), ('wall_breaker_party', 'wall breaker party'), ('ghost_parade', 'ghost parade'), ('elixir_capture', 'elixir capture'), ('dragon_hunt', 'dragon hunt'), ('duel', 'duel'), ('mega_draft_challenge', 'mega draft challenge')], default='normal', max_length=30, verbose_name='حالت بازی')),
                ('pricable', models.CharField(choices=[('free', 'رایگان'), ('premium', 'پولی')], default='premium', max_length=20, verbose_name='رایگان یا پولی')),
                ('max_participants', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(1000)], verbose_name='حداکثر شرکت\u200cکننده')),
                ('level_cap', models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(14)], verbose_name='لول کارتها')),
                ('max_losses', models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='حداکثر باخت مجاز')),
                ('time_duration', models.CharField(choices=[('30m', '30m'), ('1h', '1h'), ('2h', '2h'), ('3h', '3h'), ('4h', '4h')], default='1h', max_length=3, verbose_name='مدت تایم بازی')),
                ('entry_fee', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='هزینه ورودی')),
                ('prize_pool', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='جایزه کل')),
                ('platform_commission', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='کمیسیون پلتفرم (%)')),
                ('registration_start', models.DateTimeField(verbose_name='شروع ثبت\u200cنام')),
                ('registration_end', models.DateTimeField(verbose_name='پایان ثبت\u200cنام')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار'), ('registration', 'ثبت\u200cنام'), ('ready', 'آماده شروع'), ('ongoing', 'در حال برگزاری'), ('finished', 'پایان یافته'), ('cancelled', 'لغو شده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت')),
                ('rules', ckeditor.fields.RichTextField(blank=True, verbose_name='قوانین')),
                ('best_of', models.PositiveIntegerField(default=8, help_text='Best of 3, 5, 7', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='تعداد بازی')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('total_participants', models.PositiveIntegerField(default=0, verbose_name='تعداد شرکت\u200cکننده')),
                ('total_matches', models.PositiveIntegerField(default=0, verbose_name='تعداد مسابقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'تورنومنت',
                'verbose_name_plural': 'تورنومنت\u200cها',
                'db_table': 'tournaments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='کد دعوت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شده'), ('declined', 'رد شده'), ('expired', 'منقضی شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('message', models.TextField(blank=True, verbose_name='پیام')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tournament_invitations', to=settings.AUTH_USER_MODEL, verbose_name='دعوت شده توسط')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_invitations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر دعوت شده')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tournaments.tournament', verbose_name='تورنومنت')),
            ],
            options={
                'verbose_name': 'دعوت\u200cنامه تورنومنت',
                'verbose_name_plural': 'دعوت\u200cنامه\u200cهای تورنومنت',
                'db_table': 'tournament_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('disqualified', 'محروم شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('placement', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='رتبه')),
                ('prize_won', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='جایزه برنده شده')),
                ('matches_played', models.PositiveIntegerField(default=0, verbose_name='مسابقات انجام شده')),
                ('matches_won', models.PositiveIntegerField(default=0, verbose_name='مسابقات برده')),
                ('disqualification_reason', models.TextField(blank=True, verbose_name='دلیل محرومیت')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_participant', to='payments.payment', verbose_name='پرداخت')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament', verbose_name='تورنومنت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شرکت\u200cکننده تورنومنت',
                'verbose_name_plural': 'شرکت\u200cکنندگان تورنومنت',
                'db_table': 'tournament_participants',
                'ordering': ['placement', '-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status', 'registration_start'], name='tournaments_status_7f141e_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['start_date'], name='tournaments_start_d_47803f_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['is_featured'], name='tournaments_is_feat_6a1b87_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['slug'], name='tournaments_slug_fe5094_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentinvitation',
            unique_together={('tournament', 'invited_user')},
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['tournament', 'status'], name='tournament__tournam_7e318a_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['user', '-joined_at'], name='tournament__user_id_c46eda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together={('tournament', 'user')},
        ),
    ]
