# Generated by Django 5.2.8 on 2025-11-09 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="best_of",
            field=models.PositiveIntegerField(
                default=8,
                help_text="Best of 3, 5, 7",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="نفرات برتر",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="pricable",
            field=models.CharField(
                choices=[("free", "رایگان"), ("premium", "پرمیوم")],
                default="premium",
                max_length=20,
                verbose_name="رایگان یا پولی",
            ),
        ),
    ]
