# Generated by Django 5.2.6 on 2025-11-03 16:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('used_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان استفاده')),
            ],
            options={
                'verbose_name': 'استفاده از کوپن',
                'verbose_name_plural': 'استفاده\u200cهای کوپن',
                'db_table': 'coupon_usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه تراکنش')),
                ('payment_type', models.CharField(choices=[('deposit', 'شارژ کیف پول'), ('tournament_entry', 'ورودی تورنومنت'), ('prize', 'جایزه'), ('withdrawal', 'برداشت'), ('refund', 'بازگشت وجه'), ('penalty', 'جریمه'), ('bonus', 'پاداش')], max_length=20, verbose_name='نوع پرداخت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ')),
                ('fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='کارمزد')),
                ('final_amount', models.DecimalField(decimal_places=0, default=0, help_text='مبلغ بعد از کسر کارمزد', max_digits=12, verbose_name='مبلغ نهایی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('verifying', 'در حال تایید'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('refunded', 'بازگشت داده شده'), ('expired', 'منقضی شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('idpay', 'آیدی\u200cپی'), ('nextpay', 'نکست\u200cپی'), ('zibal', 'زیبال'), ('wallet', 'کیف پول'), ('admin', 'ادمین')], max_length=20, verbose_name='درگاه پرداخت')),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='شناسه تراکنش درگاه')),
                ('gateway_tracking_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='کد پیگیری درگاه')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='پاسخ درگاه')),
                ('gateway_callback_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای callback')),
                ('card_number', models.CharField(blank=True, max_length=4, null=True, verbose_name='شماره کارت (4 رقم آخر)')),
                ('card_holder_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام صاحب کارت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش مجدد')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('idpay', 'آیدی\u200cپی'), ('nextpay', 'نکست\u200cپی'), ('zibal', 'زیبال')], max_length=20, unique=True, verbose_name='درگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('merchant_id', models.CharField(max_length=200, verbose_name='شناسه پذیرنده')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='کلید API')),
                ('min_amount', models.DecimalField(decimal_places=0, default=1000, max_digits=10, verbose_name='حداقل مبلغ')),
                ('max_amount', models.DecimalField(decimal_places=0, default=50000000, max_digits=12, verbose_name='حداکثر مبلغ')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد کارمزد')),
                ('fixed_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='کارمزد ثابت')),
                ('payment_url', models.URLField(blank=True, verbose_name='آدرس پرداخت')),
                ('verify_url', models.URLField(blank=True, verbose_name='آدرس تایید')),
                ('callback_url', models.URLField(blank=True, verbose_name='آدرس callback')),
                ('priority', models.PositiveIntegerField(default=1, help_text='کمترین عدد = بالاترین اولویت', verbose_name='اولویت')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'پیکربندی درگاه پرداخت',
                'verbose_name_plural': 'پیکربندی\u200cهای درگاه پرداخت',
                'db_table': 'payment_gateway_configs',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='مثال: request_sent, callback_received, verified', max_length=50, verbose_name='عملیات')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای درخواست')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای پاسخ')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'لاگ پرداخت',
                'verbose_name_plural': 'لاگ\u200cهای پرداخت',
                'db_table': 'payment_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'واریز'), ('debit', 'برداشت')], db_index=True, max_length=10, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('balance_before', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='موجودی قبل')),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='موجودی بعد')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(10000)], verbose_name='مبلغ')),
                ('fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='کارمزد')),
                ('final_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ نهایی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='نام بانک')),
                ('bank_account_number', models.CharField(max_length=50, verbose_name='شماره حساب')),
                ('bank_card_number', models.CharField(help_text='16 رقم', max_length=16, verbose_name='شماره کارت')),
                ('account_holder_name', models.CharField(max_length=200, verbose_name='نام صاحب حساب')),
                ('sheba_number', models.CharField(blank=True, help_text='IR به همراه 24 رقم', max_length=26, verbose_name='شماره شبا')),
                ('tracking_code', models.CharField(blank=True, max_length=50, verbose_name='کد پیگیری')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='شماره مرجع')),
                ('user_note', models.TextField(blank=True, verbose_name='یادداشت کاربر')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ درخواست')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پردازش')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
            ],
            options={
                'verbose_name': 'برداشت',
                'verbose_name_plural': 'برداشت\u200cها',
                'db_table': 'withdrawals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع تخفیف')),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مقدار تخفیف')),
                ('max_discount', models.DecimalField(decimal_places=0, default=0, help_text='برای تخفیف درصدی - 0 = نامحدود', max_digits=10, verbose_name='حداکثر تخفیف')),
                ('min_purchase', models.DecimalField(decimal_places=0, default=0, help_text='حداقل مبلغ برای استفاده از کوپن', max_digits=10, verbose_name='حداقل خرید')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = نامحدود', verbose_name='حداکثر استفاده کل')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, verbose_name='حداکثر استفاده هر کاربر')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('valid_from', models.DateTimeField(verbose_name='معتبر از')),
                ('valid_until', models.DateTimeField(verbose_name='معتبر تا')),
                ('first_purchase_only', models.BooleanField(default=False, verbose_name='فقط خرید اول')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('expired', 'منقضی شده')], db_index=True, default='active', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='خالی = همه کاربران', related_name='allowed_coupons', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'کوپن تخفیف',
                'verbose_name_plural': 'کوپن\u200cهای تخفیف',
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
