# Generated by Django 5.2.6 on 2025-11-09 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='tournaments',
            field=models.ManyToManyField(blank=True, help_text='خالی = همه تورنومنت\u200cها', related_name='coupons', to='tournaments.tournament', verbose_name='تورنومنت\u200cهای مجاز'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='payments.coupon', verbose_name='کوپن'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='tournaments.tournament', verbose_name='تورنومنت'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='payments.payment', verbose_name='پرداخت'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.payment', verbose_name='پرداخت'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.payment', verbose_name='پرداخت'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tournaments.tournament', verbose_name='تورنومنت'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal', to='payments.payment', verbose_name='پرداخت'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='پردازش شده توسط'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code', 'status'], name='coupons_code_479ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_until'], name='coupons_valid_f_012901_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status', '-created_at'], name='payments_user_id_4471b8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type', 'status'], name='payments_payment_ebcbf8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway', '-created_at'], name='payments_gateway_7922de_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', '-used_at'], name='coupon_usag_coupon__d61383_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['user', '-used_at'], name='coupon_usag_user_id_7872e8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['payment', '-created_at'], name='payment_log_payment_84e3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='transaction_user_id_ced08a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='transaction_transac_a32e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', 'status', '-created_at'], name='withdrawals_user_id_3b5403_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status', '-created_at'], name='withdrawals_status_6bc8da_idx'),
        ),
    ]
