# Generated by Django 5.2.6 on 2025-11-03 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('tournament_created', 'تورنومنت جدید'), ('tournament_starting', 'شروع تورنومنت'), ('tournament_cancelled', 'لغو تورنومنت'), ('registration_confirmed', 'تایید ثبت\u200cنام'), ('registration_rejected', 'رد ثبت\u200cنام'), ('match_scheduled', 'زمان\u200cبندی مسابقه'), ('match_starting', 'شروع مسابقه'), ('match_reminder', 'یادآوری مسابقه'), ('match_result', 'نتیجه مسابقه'), ('opponent_submitted_result', 'حریف نتیجه ثبت کرد'), ('payment_completed', 'پرداخت موفق'), ('payment_failed', 'پرداخت ناموفق'), ('prize_awarded', 'دریافت جایزه'), ('withdrawal_requested', 'درخواست برداشت'), ('withdrawal_approved', 'تایید برداشت'), ('withdrawal_rejected', 'رد برداشت'), ('withdrawal_completed', 'تکمیل برداشت'), ('dispute_opened', 'ثبت اعتراض'), ('dispute_response', 'پاسخ به اعتراض'), ('dispute_resolved', 'حل اعتراض'), ('rank_changed', 'تغییر رتبه'), ('achievement_unlocked', 'دستاورد جدید'), ('warning', 'هشدار'), ('system', 'سیستم')], max_length=30, unique=True, verbose_name='نوع اعلان')),
                ('email_subject', models.CharField(blank=True, max_length=200, verbose_name='موضوع ایمیل')),
                ('email_body', models.TextField(blank=True, help_text='از {{variable}} برای متغیرها استفاده کنید', verbose_name='متن ایمیل')),
                ('sms_body', models.CharField(blank=True, help_text='حداکثر 160 کاراکتر', max_length=160, verbose_name='متن پیامک')),
                ('push_title', models.CharField(blank=True, max_length=100, verbose_name='عنوان پوش')),
                ('push_body', models.CharField(blank=True, max_length=200, verbose_name='متن پوش')),
                ('app_title', models.CharField(max_length=200, verbose_name='عنوان اپ')),
                ('app_body', models.TextField(verbose_name='متن اپ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'قالب اعلان',
                'verbose_name_plural': 'قالب\u200cهای اعلان',
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='ایمیل فعال')),
                ('email_tournament_created', models.BooleanField(default=True, verbose_name='تورنومنت جدید')),
                ('email_match_scheduled', models.BooleanField(default=True, verbose_name='زمان\u200cبندی مسابقه')),
                ('email_match_starting', models.BooleanField(default=True, verbose_name='شروع مسابقه')),
                ('email_match_reminder', models.BooleanField(default=True, verbose_name='یادآوری مسابقه')),
                ('email_prize_awarded', models.BooleanField(default=True, verbose_name='دریافت جایزه')),
                ('email_payment', models.BooleanField(default=True, verbose_name='پرداخت\u200cها')),
                ('email_withdrawal', models.BooleanField(default=True, verbose_name='برداشت\u200cها')),
                ('email_dispute', models.BooleanField(default=True, verbose_name='اعتراضات')),
                ('email_system', models.BooleanField(default=True, verbose_name='اعلان\u200cهای سیستم')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='پیامک فعال')),
                ('sms_match_starting', models.BooleanField(default=False, verbose_name='شروع مسابقه (پیامک)')),
                ('sms_match_reminder', models.BooleanField(default=False, verbose_name='یادآوری مسابقه (پیامک)')),
                ('sms_payment', models.BooleanField(default=False, verbose_name='پرداخت\u200cها (پیامک)')),
                ('sms_withdrawal', models.BooleanField(default=False, verbose_name='برداشت\u200cها (پیامک)')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='اعلان\u200cهای پوش')),
                ('push_tournament', models.BooleanField(default=True, verbose_name='تورنومنت\u200cها')),
                ('push_match', models.BooleanField(default=True, verbose_name='مسابقات')),
                ('push_payment', models.BooleanField(default=True, verbose_name='پرداخت\u200cها')),
                ('push_dispute', models.BooleanField(default=True, verbose_name='اعتراضات')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='ساعت\u200cهای سکوت')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='شروع سکوت')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='پایان سکوت')),
                ('digest_enabled', models.BooleanField(default=False, help_text='دریافت خلاصه اعلان\u200cها به جای تک\u200cتک', verbose_name='خلاصه اعلان\u200cها')),
                ('digest_frequency', models.CharField(blank=True, choices=[('daily', 'روزانه'), ('weekly', 'هفتگی')], default='daily', max_length=10, verbose_name='دوره ارسال خلاصه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تنظیمات اعلان',
                'verbose_name_plural': 'تنظیمات اعلان\u200cها',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('tournament_created', 'تورنومنت جدید'), ('tournament_starting', 'شروع تورنومنت'), ('tournament_cancelled', 'لغو تورنومنت'), ('registration_confirmed', 'تایید ثبت\u200cنام'), ('registration_rejected', 'رد ثبت\u200cنام'), ('match_scheduled', 'زمان\u200cبندی مسابقه'), ('match_starting', 'شروع مسابقه'), ('match_reminder', 'یادآوری مسابقه'), ('match_result', 'نتیجه مسابقه'), ('opponent_submitted_result', 'حریف نتیجه ثبت کرد'), ('payment_completed', 'پرداخت موفق'), ('payment_failed', 'پرداخت ناموفق'), ('prize_awarded', 'دریافت جایزه'), ('withdrawal_requested', 'درخواست برداشت'), ('withdrawal_approved', 'تایید برداشت'), ('withdrawal_rejected', 'رد برداشت'), ('withdrawal_completed', 'تکمیل برداشت'), ('dispute_opened', 'ثبت اعتراض'), ('dispute_response', 'پاسخ به اعتراض'), ('dispute_resolved', 'حل اعتراض'), ('rank_changed', 'تغییر رتبه'), ('achievement_unlocked', 'دستاورد جدید'), ('warning', 'هشدار'), ('system', 'سیستم')], max_length=30, verbose_name='نوع اعلان')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], default='medium', max_length=10, verbose_name='اولویت')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='لینک')),
                ('action_text', models.CharField(blank=True, help_text='مثال: مشاهده، پرداخت، تایید', max_length=50, verbose_name='متن دکمه')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خواندن')),
                ('is_sent_email', models.BooleanField(default=False, verbose_name='ایمیل ارسال شد')),
                ('is_sent_sms', models.BooleanField(default=False, verbose_name='پیامک ارسال شد')),
                ('is_sent_push', models.BooleanField(default=False, verbose_name='پوش ارسال شد')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='اطلاعات اضافی برای پردازش', verbose_name='داده\u200cهای اضافی')),
                ('expires_at', models.DateTimeField(blank=True, help_text='اعلان بعد از این تاریخ نمایش داده نمی\u200cشود', null=True, verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_63f199_idx'), models.Index(fields=['priority', '-created_at'], name='notificatio_priorit_b3d0b6_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_66996e_idx')],
            },
        ),
    ]
