# Generated by Django 5.2.6 on 2025-11-03 16:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500, verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
            ],
            options={
                'verbose_name': 'چت مسابقه',
                'verbose_name_plural': 'چت\u200cهای مسابقه',
                'db_table': 'match_chats',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_type', models.CharField(choices=[('cheating', 'تقلب'), ('no_show', 'عدم حضور حریف'), ('other', 'سایر')], default='wrong_result', max_length=20, verbose_name='نوع اعتراض')),
                ('reason', models.TextField(verbose_name='دلیل اعتراض')),
                ('evidence', models.ImageField(blank=True, help_text='تصویر مدرک اعتراض', null=True, upload_to='dispute_evidence/%Y/%m/%d/', verbose_name='مدرک')),
                ('additional_evidence', models.JSONField(blank=True, default=list, help_text='لینک\u200cها یا توضیحات اضافی', verbose_name='مدارک اضافی')),
                ('status', models.CharField(choices=[('open', 'باز'), ('under_review', 'در حال بررسی'), ('resolved', 'حل شده'), ('rejected', 'رد شده')], default='open', max_length=20, verbose_name='وضعیت')),
                ('admin_response', models.TextField(blank=True, verbose_name='پاسخ ادمین')),
                ('resolution_action', models.CharField(blank=True, help_text='مثال: نتیجه اصلاح شد، بازیکن محروم شد، و غیره', max_length=200, verbose_name='اقدام انجام شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حل')),
                ('priority', models.PositiveIntegerField(default=1, help_text='1=کم، 5=خیلی زیاد', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='اولویت')),
            ],
            options={
                'verbose_name': 'اعتراض مسابقه',
                'verbose_name_plural': 'اعتراضات مسابقات',
                'db_table': 'match_disputes',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.PositiveIntegerField(verbose_name='شماره بازی')),
                ('player1_crowns', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='کرون بازیکن 1')),
                ('player2_crowns', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='کرون بازیکن 2')),
                ('player1_towers_destroyed', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='برج\u200cهای تخریب شده بازیکن 1')),
                ('player2_towers_destroyed', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='برج\u200cهای تخریب شده بازیکن 2')),
                ('is_overtime', models.BooleanField(default=False, verbose_name='اضافه وقت')),
                ('screenshot', models.ImageField(blank=True, help_text='اسکرین\u200cشات نتیجه بازی', null=True, upload_to='match_screenshots/%Y/%m/%d/', verbose_name='اسکرین\u200cشات')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)], verbose_name='مدت بازی (ثانیه)')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بازی')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_games', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_games', to=settings.AUTH_USER_MODEL, verbose_name='تایید شده توسط')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to=settings.AUTH_USER_MODEL, verbose_name='برنده')),
            ],
            options={
                'verbose_name': 'بازی',
                'verbose_name_plural': 'بازی\u200cها',
                'db_table': 'games',
                'ordering': ['match', 'game_number'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField(verbose_name='شماره مسابقه')),
                ('best_of', models.PositiveIntegerField(default=3, help_text='Best of 3, 5, 7, etc.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='تعداد بازی')),
                ('player1_wins', models.PositiveIntegerField(default=0, verbose_name='برد بازیکن 1')),
                ('player2_wins', models.PositiveIntegerField(default=0, verbose_name='برد بازیکن 2')),
                ('status', models.CharField(choices=[('scheduled', 'زمان\u200cبندی شده'), ('ready', 'آماده'), ('ongoing', 'در حال بازی'), ('waiting_result', 'در انتظار نتیجه'), ('completed', 'تمام شده'), ('disputed', 'اعتراض شده'), ('cancelled', 'لغو شده')], default='scheduled', max_length=20, verbose_name='وضعیت')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان برنامه\u200cریزی شده')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع بازی')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان بازی')),
                ('player1_submitted_result', models.BooleanField(default=False, verbose_name='بازیکن 1 نتیجه ثبت کرد')),
                ('player2_submitted_result', models.BooleanField(default=False, verbose_name='بازیکن 2 نتیجه ثبت کرد')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('admin_verified', models.BooleanField(default=False, verbose_name='تایید ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to=settings.AUTH_USER_MODEL, verbose_name='بازیکن 1')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to=settings.AUTH_USER_MODEL, verbose_name='بازیکن 2')),
            ],
            options={
                'verbose_name': 'مسابقه',
                'verbose_name_plural': 'مسابقات',
                'db_table': 'matches',
                'ordering': ['tournament', 'match_number'],
            },
        ),
    ]
