# Generated by Django 5.2.6 on 2025-11-03 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament', verbose_name='تورنومنت'),
        ),
        migrations.AddField(
            model_name='match',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_matches', to=settings.AUTH_USER_MODEL, verbose_name='تایید شده توسط'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to=settings.AUTH_USER_MODEL, verbose_name='برنده'),
        ),
        migrations.AddField(
            model_name='game',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='matches.match', verbose_name='مسابقه'),
        ),
        migrations.AddField(
            model_name='matchchat',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='matches.match', verbose_name='مسابقه'),
        ),
        migrations.AddField(
            model_name='matchchat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_match_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده'),
        ),
        migrations.AddField(
            model_name='matchdispute',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='matches.game', verbose_name='بازی'),
        ),
        migrations.AddField(
            model_name='matchdispute',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='matches.match', verbose_name='مسابقه'),
        ),
        migrations.AddField(
            model_name='matchdispute',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_disputes', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده'),
        ),
        migrations.AddField(
            model_name='matchdispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL, verbose_name='حل شده توسط'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'status'], name='matches_tournam_a71fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['player1', 'player2'], name='matches_player1_c1064a_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['scheduled_time'], name='matches_schedul_7cadb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('player1', models.F('player2')), _negated=True), name='different_players'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['match', 'game_number'], name='games_match_i_dca1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['is_verified'], name='games_is_veri_6cee62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('match', 'game_number')},
        ),
        migrations.AddIndex(
            model_name='matchchat',
            index=models.Index(fields=['match', 'created_at'], name='match_chats_match_i_015fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='matchdispute',
            index=models.Index(fields=['status', '-created_at'], name='match_dispu_status_466dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='matchdispute',
            index=models.Index(fields=['match', 'reporter'], name='match_dispu_match_i_f85731_idx'),
        ),
    ]
